<?php

return [
['id_kabupaten' => '1101', 'nama_kabupaten' => 'Kab. Simeulue', 'provinsi_id' => '11'],
['id_kabupaten' => '1102', 'nama_kabupaten' => 'Kab. Aceh Singkil', 'provinsi_id' => '11'],
['id_kabupaten' => '1103', 'nama_kabupaten' => 'Kab. Aceh Selatan', 'provinsi_id' => '11'],
['id_kabupaten' => '1104', 'nama_kabupaten' => 'Kab. Aceh Tenggara', 'provinsi_id' => '11'],
['id_kabupaten' => '1105', 'nama_kabupaten' => 'Kab. Aceh Timur', 'provinsi_id' => '11'],
['id_kabupaten' => '1106', 'nama_kabupaten' => 'Kab. Aceh Tengah', 'provinsi_id' => '11'],
['id_kabupaten' => '1107', 'nama_kabupaten' => 'Kab. Aceh Barat', 'provinsi_id' => '11'],
['id_kabupaten' => '1108', 'nama_kabupaten' => 'Kab. Aceh Besar', 'provinsi_id' => '11'],
['id_kabupaten' => '1109', 'nama_kabupaten' => 'Kab. Pidie', 'provinsi_id' => '11'],
['id_kabupaten' => '1110', 'nama_kabupaten' => 'Kab. Bireuen', 'provinsi_id' => '11'],
['id_kabupaten' => '1111', 'nama_kabupaten' => 'Kab. Aceh Utara', 'provinsi_id' => '11'],
['id_kabupaten' => '1112', 'nama_kabupaten' => 'Kab. Aceh Barat Daya', 'provinsi_id' => '11'],
['id_kabupaten' => '1113', 'nama_kabupaten' => 'Kab. Gayo Lues', 'provinsi_id' => '11'],
['id_kabupaten' => '1114', 'nama_kabupaten' => 'Kab. Aceh Tamiang', 'provinsi_id' => '11'],
['id_kabupaten' => '1115', 'nama_kabupaten' => 'Kab. Nagan Raya', 'provinsi_id' => '11'],
['id_kabupaten' => '1116', 'nama_kabupaten' => 'Kab. Aceh Jaya', 'provinsi_id' => '11'],
['id_kabupaten' => '1117', 'nama_kabupaten' => 'Kab. Bener Meriah', 'provinsi_id' => '11'],
['id_kabupaten' => '1118', 'nama_kabupaten' => 'Kab. Pidie Jaya', 'provinsi_id' => '11'],
['id_kabupaten' => '1171', 'nama_kabupaten' => 'Kota Banda Aceh', 'provinsi_id' => '11'],
['id_kabupaten' => '1172', 'nama_kabupaten' => 'Kota Sabang', 'provinsi_id' => '11'],
['id_kabupaten' => '1173', 'nama_kabupaten' => 'Kota Langsa', 'provinsi_id' => '11'],
['id_kabupaten' => '1174', 'nama_kabupaten' => 'Kota Lhokseumawe', 'provinsi_id' => '11'],
['id_kabupaten' => '1175', 'nama_kabupaten' => 'Kota Subulussalam', 'provinsi_id' => '11'],
['id_kabupaten' => '1201', 'nama_kabupaten' => 'Kab. Nias', 'provinsi_id' => '12'],
['id_kabupaten' => '1202', 'nama_kabupaten' => 'Kab. Mandailing Natal', 'provinsi_id' => '12'],
['id_kabupaten' => '1203', 'nama_kabupaten' => 'Kab. Tapanuli Selatan', 'provinsi_id' => '12'],
['id_kabupaten' => '1204', 'nama_kabupaten' => 'Kab. Tapanuli Tengah', 'provinsi_id' => '12'],
['id_kabupaten' => '1205', 'nama_kabupaten' => 'Kab. Tapanuli Utara', 'provinsi_id' => '12'],
['id_kabupaten' => '1206', 'nama_kabupaten' => 'Kab. Toba Samosir', 'provinsi_id' => '12'],
['id_kabupaten' => '1207', 'nama_kabupaten' => 'Kab. Labuhan Batu', 'provinsi_id' => '12'],
['id_kabupaten' => '1208', 'nama_kabupaten' => 'Kab. Asahan', 'provinsi_id' => '12'],
['id_kabupaten' => '1209', 'nama_kabupaten' => 'Kab. Simalungun', 'provinsi_id' => '12'],
['id_kabupaten' => '1210', 'nama_kabupaten' => 'Kab. Dairi', 'provinsi_id' => '12'],
['id_kabupaten' => '1211', 'nama_kabupaten' => 'Kab. Karo', 'provinsi_id' => '12'],
['id_kabupaten' => '1212', 'nama_kabupaten' => 'Kab. Deli Serdang', 'provinsi_id' => '12'],
['id_kabupaten' => '1213', 'nama_kabupaten' => 'Kab. Langkat', 'provinsi_id' => '12'],
['id_kabupaten' => '1214', 'nama_kabupaten' => 'Kab. Nias Selatan', 'provinsi_id' => '12'],
['id_kabupaten' => '1215', 'nama_kabupaten' => 'Kab. Humbang Hasundutan', 'provinsi_id' => '12'],
['id_kabupaten' => '1216', 'nama_kabupaten' => 'Kab. Pakpak Bharat', 'provinsi_id' => '12'],
['id_kabupaten' => '1217', 'nama_kabupaten' => 'Kab. Samosir', 'provinsi_id' => '12'],
['id_kabupaten' => '1218', 'nama_kabupaten' => 'Kab. Serdang Bedagai', 'provinsi_id' => '12'],
['id_kabupaten' => '1219', 'nama_kabupaten' => 'Kab. Batu Bara', 'provinsi_id' => '12'],
['id_kabupaten' => '1220', 'nama_kabupaten' => 'Kab. Padang Lawas Utara', 'provinsi_id' => '12'],
['id_kabupaten' => '1221', 'nama_kabupaten' => 'Kab. Padang Lawas', 'provinsi_id' => '12'],
['id_kabupaten' => '1222', 'nama_kabupaten' => 'Kab. Labuhan Batu Selatan', 'provinsi_id' => '12'],
['id_kabupaten' => '1223', 'nama_kabupaten' => 'Kab. Labuhan Batu Utara', 'provinsi_id' => '12'],
['id_kabupaten' => '1224', 'nama_kabupaten' => 'Kab. Nias Utara', 'provinsi_id' => '12'],
['id_kabupaten' => '1225', 'nama_kabupaten' => 'Kab. Nias Barat', 'provinsi_id' => '12'],
['id_kabupaten' => '1271', 'nama_kabupaten' => 'Kota Sibolga', 'provinsi_id' => '12'],
['id_kabupaten' => '1272', 'nama_kabupaten' => 'Kota Tanjung Balai', 'provinsi_id' => '12'],
['id_kabupaten' => '1273', 'nama_kabupaten' => 'Kota Pematang Siantar', 'provinsi_id' => '12'],
['id_kabupaten' => '1274', 'nama_kabupaten' => 'Kota Tebing Tinggi', 'provinsi_id' => '12'],
['id_kabupaten' => '1275', 'nama_kabupaten' => 'Kota Medan', 'provinsi_id' => '12'],
['id_kabupaten' => '1276', 'nama_kabupaten' => 'Kota Binjai', 'provinsi_id' => '12'],
['id_kabupaten' => '1277', 'nama_kabupaten' => 'Kota Padangsidimpuan', 'provinsi_id' => '12'],
['id_kabupaten' => '1278', 'nama_kabupaten' => 'Kota Gunungsitoli', 'provinsi_id' => '12'],
['id_kabupaten' => '1301', 'nama_kabupaten' => 'Kab. Kepulauan Mentawai', 'provinsi_id' => '13'],
['id_kabupaten' => '1302', 'nama_kabupaten' => 'Kab. Pesisir Selatan', 'provinsi_id' => '13'],
['id_kabupaten' => '1303', 'nama_kabupaten' => 'Kab. Solok', 'provinsi_id' => '13'],
['id_kabupaten' => '1304', 'nama_kabupaten' => 'Kab. Sijunjung', 'provinsi_id' => '13'],
['id_kabupaten' => '1305', 'nama_kabupaten' => 'Kab. Tanah Datar', 'provinsi_id' => '13'],
['id_kabupaten' => '1306', 'nama_kabupaten' => 'Kab. Padang Pariaman', 'provinsi_id' => '13'],
['id_kabupaten' => '1307', 'nama_kabupaten' => 'Kab. Agam', 'provinsi_id' => '13'],
['id_kabupaten' => '1308', 'nama_kabupaten' => 'Kab. Lima Puluh Kota', 'provinsi_id' => '13'],
['id_kabupaten' => '1309', 'nama_kabupaten' => 'Kab. Pasaman', 'provinsi_id' => '13'],
['id_kabupaten' => '1310', 'nama_kabupaten' => 'Kab. Solok Selatan', 'provinsi_id' => '13'],
['id_kabupaten' => '1311', 'nama_kabupaten' => 'Kab. Dharmasraya', 'provinsi_id' => '13'],
['id_kabupaten' => '1312', 'nama_kabupaten' => 'Kab. Pasaman Barat', 'provinsi_id' => '13'],
['id_kabupaten' => '1371', 'nama_kabupaten' => 'Kota Padang', 'provinsi_id' => '13'],
['id_kabupaten' => '1372', 'nama_kabupaten' => 'Kota Solok', 'provinsi_id' => '13'],
['id_kabupaten' => '1373', 'nama_kabupaten' => 'Kota Sawah Lunto', 'provinsi_id' => '13'],
['id_kabupaten' => '1374', 'nama_kabupaten' => 'Kota Padang Panjang', 'provinsi_id' => '13'],
['id_kabupaten' => '1375', 'nama_kabupaten' => 'Kota Bukittinggi', 'provinsi_id' => '13'],
['id_kabupaten' => '1376', 'nama_kabupaten' => 'Kota Payakumbuh', 'provinsi_id' => '13'],
['id_kabupaten' => '1377', 'nama_kabupaten' => 'Kota Pariaman', 'provinsi_id' => '13'],
['id_kabupaten' => '1401', 'nama_kabupaten' => 'Kab. Kuantan Singingi', 'provinsi_id' => '14'],
['id_kabupaten' => '1402', 'nama_kabupaten' => 'Kab. Indragiri Hulu', 'provinsi_id' => '14'],
['id_kabupaten' => '1403', 'nama_kabupaten' => 'Kab. Indragiri Hilir', 'provinsi_id' => '14'],
['id_kabupaten' => '1404', 'nama_kabupaten' => 'Kab. Pelalawan', 'provinsi_id' => '14'],
['id_kabupaten' => '1405', 'nama_kabupaten' => 'Kab. S I A K', 'provinsi_id' => '14'],
['id_kabupaten' => '1406', 'nama_kabupaten' => 'Kab. Kampar', 'provinsi_id' => '14'],
['id_kabupaten' => '1407', 'nama_kabupaten' => 'Kab. Rokan Hulu', 'provinsi_id' => '14'],
['id_kabupaten' => '1408', 'nama_kabupaten' => 'Kab. Bengkalis', 'provinsi_id' => '14'],
['id_kabupaten' => '1409', 'nama_kabupaten' => 'Kab. Rokan Hilir', 'provinsi_id' => '14'],
['id_kabupaten' => '1410', 'nama_kabupaten' => 'Kab. Kepulauan Meranti', 'provinsi_id' => '14'],
['id_kabupaten' => '1471', 'nama_kabupaten' => 'Kota Pekanbaru', 'provinsi_id' => '14'],
['id_kabupaten' => '1473', 'nama_kabupaten' => 'Kota D U M A I', 'provinsi_id' => '14'],
['id_kabupaten' => '1501', 'nama_kabupaten' => 'Kab. Kerinci', 'provinsi_id' => '15'],
['id_kabupaten' => '1502', 'nama_kabupaten' => 'Kab. Merangin', 'provinsi_id' => '15'],
['id_kabupaten' => '1503', 'nama_kabupaten' => 'Kab. Sarolangun', 'provinsi_id' => '15'],
['id_kabupaten' => '1504', 'nama_kabupaten' => 'Kab. Batang Hari', 'provinsi_id' => '15'],
['id_kabupaten' => '1505', 'nama_kabupaten' => 'Kab. Muaro Jambi', 'provinsi_id' => '15'],
['id_kabupaten' => '1506', 'nama_kabupaten' => 'Kab. Tanjung Jabung Timur', 'provinsi_id' => '15'],
['id_kabupaten' => '1507', 'nama_kabupaten' => 'Kab. Tanjung Jabung Barat', 'provinsi_id' => '15'],
['id_kabupaten' => '1508', 'nama_kabupaten' => 'Kab. Tebo', 'provinsi_id' => '15'],
['id_kabupaten' => '1509', 'nama_kabupaten' => 'Kab. Bungo', 'provinsi_id' => '15'],
['id_kabupaten' => '1571', 'nama_kabupaten' => 'Kota Jambi', 'provinsi_id' => '15'],
['id_kabupaten' => '1572', 'nama_kabupaten' => 'Kota Sungai Penuh', 'provinsi_id' => '15'],
['id_kabupaten' => '1601', 'nama_kabupaten' => 'Kab. Ogan Komering Ulu', 'provinsi_id' => '16'],
['id_kabupaten' => '1602', 'nama_kabupaten' => 'Kab. Ogan Komering Ilir', 'provinsi_id' => '16'],
['id_kabupaten' => '1603', 'nama_kabupaten' => 'Kab. Muara Enim', 'provinsi_id' => '16'],
['id_kabupaten' => '1604', 'nama_kabupaten' => 'Kab. Lahat', 'provinsi_id' => '16'],
['id_kabupaten' => '1605', 'nama_kabupaten' => 'Kab. Musi Rawas', 'provinsi_id' => '16'],
['id_kabupaten' => '1606', 'nama_kabupaten' => 'Kab. Musi Banyuasin', 'provinsi_id' => '16'],
['id_kabupaten' => '1607', 'nama_kabupaten' => 'Kab. Banyu Asin', 'provinsi_id' => '16'],
['id_kabupaten' => '1608', 'nama_kabupaten' => 'Kab. Ogan Komering Ulu Selatan', 'provinsi_id' => '16'],
['id_kabupaten' => '1609', 'nama_kabupaten' => 'Kab. Ogan Komering Ulu Timur', 'provinsi_id' => '16'],
['id_kabupaten' => '1610', 'nama_kabupaten' => 'Kab. Ogan Ilir', 'provinsi_id' => '16'],
['id_kabupaten' => '1611', 'nama_kabupaten' => 'Kab. Empat Lawang', 'provinsi_id' => '16'],
['id_kabupaten' => '1671', 'nama_kabupaten' => 'Kota Palembang', 'provinsi_id' => '16'],
['id_kabupaten' => '1672', 'nama_kabupaten' => 'Kota Prabumulih', 'provinsi_id' => '16'],
['id_kabupaten' => '1673', 'nama_kabupaten' => 'Kota Pagar Alam', 'provinsi_id' => '16'],
['id_kabupaten' => '1674', 'nama_kabupaten' => 'Kota Lubuklinggau', 'provinsi_id' => '16'],
['id_kabupaten' => '1701', 'nama_kabupaten' => 'Kab. Bengkulu Selatan', 'provinsi_id' => '17'],
['id_kabupaten' => '1702', 'nama_kabupaten' => 'Kab. Rejang Lebong', 'provinsi_id' => '17'],
['id_kabupaten' => '1703', 'nama_kabupaten' => 'Kab. Bengkulu Utara', 'provinsi_id' => '17'],
['id_kabupaten' => '1704', 'nama_kabupaten' => 'Kab. Kaur', 'provinsi_id' => '17'],
['id_kabupaten' => '1705', 'nama_kabupaten' => 'Kab. Seluma', 'provinsi_id' => '17'],
['id_kabupaten' => '1706', 'nama_kabupaten' => 'Kab. Mukomuko', 'provinsi_id' => '17'],
['id_kabupaten' => '1707', 'nama_kabupaten' => 'Kab. Lebong', 'provinsi_id' => '17'],
['id_kabupaten' => '1708', 'nama_kabupaten' => 'Kab. Kepahiang', 'provinsi_id' => '17'],
['id_kabupaten' => '1709', 'nama_kabupaten' => 'Kab. Bengkulu Tengah', 'provinsi_id' => '17'],
['id_kabupaten' => '1771', 'nama_kabupaten' => 'Kota Bengkulu', 'provinsi_id' => '17'],
['id_kabupaten' => '1801', 'nama_kabupaten' => 'Kab. Lampung Barat', 'provinsi_id' => '18'],
['id_kabupaten' => '1802', 'nama_kabupaten' => 'Kab. Tanggamus', 'provinsi_id' => '18'],
['id_kabupaten' => '1803', 'nama_kabupaten' => 'Kab. Lampung Selatan', 'provinsi_id' => '18'],
['id_kabupaten' => '1804', 'nama_kabupaten' => 'Kab. Lampung Timur', 'provinsi_id' => '18'],
['id_kabupaten' => '1805', 'nama_kabupaten' => 'Kab. Lampung Tengah', 'provinsi_id' => '18'],
['id_kabupaten' => '1806', 'nama_kabupaten' => 'Kab. Lampung Utara', 'provinsi_id' => '18'],
['id_kabupaten' => '1807', 'nama_kabupaten' => 'Kab. Way Kanan', 'provinsi_id' => '18'],
['id_kabupaten' => '1808', 'nama_kabupaten' => 'Kab. Tulangbawang', 'provinsi_id' => '18'],
['id_kabupaten' => '1809', 'nama_kabupaten' => 'Kab. Pesawaran', 'provinsi_id' => '18'],
['id_kabupaten' => '1810', 'nama_kabupaten' => 'Kab. Pringsewu', 'provinsi_id' => '18'],
['id_kabupaten' => '1811', 'nama_kabupaten' => 'Kab. Mesuji', 'provinsi_id' => '18'],
['id_kabupaten' => '1812', 'nama_kabupaten' => 'Kab. Tulang Bawang Barat', 'provinsi_id' => '18'],
['id_kabupaten' => '1813', 'nama_kabupaten' => 'Kab. Pesisir Barat', 'provinsi_id' => '18'],
['id_kabupaten' => '1871', 'nama_kabupaten' => 'Kota Bandar Lampung', 'provinsi_id' => '18'],
['id_kabupaten' => '1872', 'nama_kabupaten' => 'Kota Metro', 'provinsi_id' => '18'],
['id_kabupaten' => '1901', 'nama_kabupaten' => 'Kab. Bangka', 'provinsi_id' => '19'],
['id_kabupaten' => '1902', 'nama_kabupaten' => 'Kab. Belitung', 'provinsi_id' => '19'],
['id_kabupaten' => '1903', 'nama_kabupaten' => 'Kab. Bangka Barat', 'provinsi_id' => '19'],
['id_kabupaten' => '1904', 'nama_kabupaten' => 'Kab. Bangka Tengah', 'provinsi_id' => '19'],
['id_kabupaten' => '1905', 'nama_kabupaten' => 'Kab. Bangka Selatan', 'provinsi_id' => '19'],
['id_kabupaten' => '1906', 'nama_kabupaten' => 'Kab. Belitung Timur', 'provinsi_id' => '19'],
['id_kabupaten' => '1971', 'nama_kabupaten' => 'Kota Pangkal Pinang', 'provinsi_id' => '19'],
['id_kabupaten' => '2101', 'nama_kabupaten' => 'Kab. Karimun', 'provinsi_id' => '21'],
['id_kabupaten' => '2102', 'nama_kabupaten' => 'Kab. Bintan', 'provinsi_id' => '21'],
['id_kabupaten' => '2103', 'nama_kabupaten' => 'Kab. Natuna', 'provinsi_id' => '21'],
['id_kabupaten' => '2104', 'nama_kabupaten' => 'Kab. Lingga', 'provinsi_id' => '21'],
['id_kabupaten' => '2105', 'nama_kabupaten' => 'Kab. Kepulauan Anambas', 'provinsi_id' => '21'],
['id_kabupaten' => '2171', 'nama_kabupaten' => 'Kota B A T A M', 'provinsi_id' => '21'],
['id_kabupaten' => '2172', 'nama_kabupaten' => 'Kota Tanjung Pinang', 'provinsi_id' => '21'],
['id_kabupaten' => '3101', 'nama_kabupaten' => 'Kab. Kepulauan Seribu', 'provinsi_id' => '31'],
['id_kabupaten' => '3171', 'nama_kabupaten' => 'Kota Jakarta Selatan', 'provinsi_id' => '31'],
['id_kabupaten' => '3172', 'nama_kabupaten' => 'Kota Jakarta Timur', 'provinsi_id' => '31'],
['id_kabupaten' => '3173', 'nama_kabupaten' => 'Kota Jakarta Pusat', 'provinsi_id' => '31'],
['id_kabupaten' => '3174', 'nama_kabupaten' => 'Kota Jakarta Barat', 'provinsi_id' => '31'],
['id_kabupaten' => '3175', 'nama_kabupaten' => 'Kota Jakarta Utara', 'provinsi_id' => '31'],
['id_kabupaten' => '3201', 'nama_kabupaten' => 'Kab. Bogor', 'provinsi_id' => '32'],
['id_kabupaten' => '3202', 'nama_kabupaten' => 'Kab. Sukabumi', 'provinsi_id' => '32'],
['id_kabupaten' => '3203', 'nama_kabupaten' => 'Kab. Cianjur', 'provinsi_id' => '32'],
['id_kabupaten' => '3204', 'nama_kabupaten' => 'Kab. Bandung', 'provinsi_id' => '32'],
['id_kabupaten' => '3205', 'nama_kabupaten' => 'Kab. Garut', 'provinsi_id' => '32'],
['id_kabupaten' => '3206', 'nama_kabupaten' => 'Kab. Tasikmalaya', 'provinsi_id' => '32'],
['id_kabupaten' => '3207', 'nama_kabupaten' => 'Kab. Ciamis', 'provinsi_id' => '32'],
['id_kabupaten' => '3208', 'nama_kabupaten' => 'Kab. Kuningan', 'provinsi_id' => '32'],
['id_kabupaten' => '3209', 'nama_kabupaten' => 'Kab. Cirebon', 'provinsi_id' => '32'],
['id_kabupaten' => '3210', 'nama_kabupaten' => 'Kab. Majalengka', 'provinsi_id' => '32'],
['id_kabupaten' => '3211', 'nama_kabupaten' => 'Kab. Sumedang', 'provinsi_id' => '32'],
['id_kabupaten' => '3212', 'nama_kabupaten' => 'Kab. Indramayu', 'provinsi_id' => '32'],
['id_kabupaten' => '3213', 'nama_kabupaten' => 'Kab. Subang', 'provinsi_id' => '32'],
['id_kabupaten' => '3214', 'nama_kabupaten' => 'Kab. Purwakarta', 'provinsi_id' => '32'],
['id_kabupaten' => '3215', 'nama_kabupaten' => 'Kab. Karawang', 'provinsi_id' => '32'],
['id_kabupaten' => '3216', 'nama_kabupaten' => 'Kab. Bekasi', 'provinsi_id' => '32'],
['id_kabupaten' => '3217', 'nama_kabupaten' => 'Kab. Bandung Barat', 'provinsi_id' => '32'],
['id_kabupaten' => '3218', 'nama_kabupaten' => 'Kab. Pangandaran', 'provinsi_id' => '32'],
['id_kabupaten' => '3271', 'nama_kabupaten' => 'Kota Bogor', 'provinsi_id' => '32'],
['id_kabupaten' => '3272', 'nama_kabupaten' => 'Kota Sukabumi', 'provinsi_id' => '32'],
['id_kabupaten' => '3273', 'nama_kabupaten' => 'Kota Bandung', 'provinsi_id' => '32'],
['id_kabupaten' => '3274', 'nama_kabupaten' => 'Kota Cirebon', 'provinsi_id' => '32'],
['id_kabupaten' => '3275', 'nama_kabupaten' => 'Kota Bekasi', 'provinsi_id' => '32'],
['id_kabupaten' => '3276', 'nama_kabupaten' => 'Kota Depok', 'provinsi_id' => '32'],
['id_kabupaten' => '3277', 'nama_kabupaten' => 'Kota Cimahi', 'provinsi_id' => '32'],
['id_kabupaten' => '3278', 'nama_kabupaten' => 'Kota Tasikmalaya', 'provinsi_id' => '32'],
['id_kabupaten' => '3279', 'nama_kabupaten' => 'Kota Banjar', 'provinsi_id' => '32'],
['id_kabupaten' => '3301', 'nama_kabupaten' => 'Kab. Cilacap', 'provinsi_id' => '33'],
['id_kabupaten' => '3302', 'nama_kabupaten' => 'Kab. Banyumas', 'provinsi_id' => '33'],
['id_kabupaten' => '3303', 'nama_kabupaten' => 'Kab. Purbalingga', 'provinsi_id' => '33'],
['id_kabupaten' => '3304', 'nama_kabupaten' => 'Kab. Banjarnegara', 'provinsi_id' => '33'],
['id_kabupaten' => '3305', 'nama_kabupaten' => 'Kab. Kebumen', 'provinsi_id' => '33'],
['id_kabupaten' => '3306', 'nama_kabupaten' => 'Kab. Purworejo', 'provinsi_id' => '33'],
['id_kabupaten' => '3307', 'nama_kabupaten' => 'Kab. Wonosobo', 'provinsi_id' => '33'],
['id_kabupaten' => '3308', 'nama_kabupaten' => 'Kab. Magelang', 'provinsi_id' => '33'],
['id_kabupaten' => '3309', 'nama_kabupaten' => 'Kab. Boyolali', 'provinsi_id' => '33'],
['id_kabupaten' => '3310', 'nama_kabupaten' => 'Kab. Klaten', 'provinsi_id' => '33'],
['id_kabupaten' => '3311', 'nama_kabupaten' => 'Kab. Sukoharjo', 'provinsi_id' => '33'],
['id_kabupaten' => '3312', 'nama_kabupaten' => 'Kab. Wonogiri', 'provinsi_id' => '33'],
['id_kabupaten' => '3313', 'nama_kabupaten' => 'Kab. Karanganyar', 'provinsi_id' => '33'],
['id_kabupaten' => '3314', 'nama_kabupaten' => 'Kab. Sragen', 'provinsi_id' => '33'],
['id_kabupaten' => '3315', 'nama_kabupaten' => 'Kab. Grobogan', 'provinsi_id' => '33'],
['id_kabupaten' => '3316', 'nama_kabupaten' => 'Kab. Blora', 'provinsi_id' => '33'],
['id_kabupaten' => '3317', 'nama_kabupaten' => 'Kab. Rembang', 'provinsi_id' => '33'],
['id_kabupaten' => '3318', 'nama_kabupaten' => 'Kab. Pati', 'provinsi_id' => '33'],
['id_kabupaten' => '3319', 'nama_kabupaten' => 'Kab. Kudus', 'provinsi_id' => '33'],
['id_kabupaten' => '3320', 'nama_kabupaten' => 'Kab. Jepara', 'provinsi_id' => '33'],
['id_kabupaten' => '3321', 'nama_kabupaten' => 'Kab. Demak', 'provinsi_id' => '33'],
['id_kabupaten' => '3322', 'nama_kabupaten' => 'Kab. Semarang', 'provinsi_id' => '33'],
['id_kabupaten' => '3323', 'nama_kabupaten' => 'Kab. Temanggung', 'provinsi_id' => '33'],
['id_kabupaten' => '3324', 'nama_kabupaten' => 'Kab. Kendal', 'provinsi_id' => '33'],
['id_kabupaten' => '3325', 'nama_kabupaten' => 'Kab. Batang', 'provinsi_id' => '33'],
['id_kabupaten' => '3326', 'nama_kabupaten' => 'Kab. Pekalongan', 'provinsi_id' => '33'],
['id_kabupaten' => '3327', 'nama_kabupaten' => 'Kab. Pemalang', 'provinsi_id' => '33'],
['id_kabupaten' => '3328', 'nama_kabupaten' => 'Kab. Tegal', 'provinsi_id' => '33'],
['id_kabupaten' => '3329', 'nama_kabupaten' => 'Kab. Brebes', 'provinsi_id' => '33'],
['id_kabupaten' => '3371', 'nama_kabupaten' => 'Kota Magelang', 'provinsi_id' => '33'],
['id_kabupaten' => '3372', 'nama_kabupaten' => 'Kota Surakarta', 'provinsi_id' => '33'],
['id_kabupaten' => '3373', 'nama_kabupaten' => 'Kota Salatiga', 'provinsi_id' => '33'],
['id_kabupaten' => '3374', 'nama_kabupaten' => 'Kota Semarang', 'provinsi_id' => '33'],
['id_kabupaten' => '3375', 'nama_kabupaten' => 'Kota Pekalongan', 'provinsi_id' => '33'],
['id_kabupaten' => '3376', 'nama_kabupaten' => 'Kota Tegal', 'provinsi_id' => '33'],
['id_kabupaten' => '3401', 'nama_kabupaten' => 'Kab. Kulon Progo', 'provinsi_id' => '34'],
['id_kabupaten' => '3402', 'nama_kabupaten' => 'Kab. Bantul', 'provinsi_id' => '34'],
['id_kabupaten' => '3403', 'nama_kabupaten' => 'Kab. Gunung Kidul', 'provinsi_id' => '34'],
['id_kabupaten' => '3404', 'nama_kabupaten' => 'Kab. Sleman', 'provinsi_id' => '34'],
['id_kabupaten' => '3471', 'nama_kabupaten' => 'Kota Yogyakarta', 'provinsi_id' => '34'],
['id_kabupaten' => '3501', 'nama_kabupaten' => 'Kab. Pacitan', 'provinsi_id' => '35'],
['id_kabupaten' => '3502', 'nama_kabupaten' => 'Kab. Ponorogo', 'provinsi_id' => '35'],
['id_kabupaten' => '3503', 'nama_kabupaten' => 'Kab. Trenggalek', 'provinsi_id' => '35'],
['id_kabupaten' => '3504', 'nama_kabupaten' => 'Kab. Tulungagung', 'provinsi_id' => '35'],
['id_kabupaten' => '3505', 'nama_kabupaten' => 'Kab. Blitar', 'provinsi_id' => '35'],
['id_kabupaten' => '3506', 'nama_kabupaten' => 'Kab. Kediri', 'provinsi_id' => '35'],
['id_kabupaten' => '3507', 'nama_kabupaten' => 'Kab. Malang', 'provinsi_id' => '35'],
['id_kabupaten' => '3508', 'nama_kabupaten' => 'Kab. Lumajang', 'provinsi_id' => '35'],
['id_kabupaten' => '3509', 'nama_kabupaten' => 'Kab. Jember', 'provinsi_id' => '35'],
['id_kabupaten' => '3510', 'nama_kabupaten' => 'Kab. Banyuwangi', 'provinsi_id' => '35'],
['id_kabupaten' => '3511', 'nama_kabupaten' => 'Kab. Bondowoso', 'provinsi_id' => '35'],
['id_kabupaten' => '3512', 'nama_kabupaten' => 'Kab. Situbondo', 'provinsi_id' => '35'],
['id_kabupaten' => '3513', 'nama_kabupaten' => 'Kab. Probolinggo', 'provinsi_id' => '35'],
['id_kabupaten' => '3514', 'nama_kabupaten' => 'Kab. Pasuruan', 'provinsi_id' => '35'],
['id_kabupaten' => '3515', 'nama_kabupaten' => 'Kab. Sidoarjo', 'provinsi_id' => '35'],
['id_kabupaten' => '3516', 'nama_kabupaten' => 'Kab. Mojokerto', 'provinsi_id' => '35'],
['id_kabupaten' => '3517', 'nama_kabupaten' => 'Kab. Jombang', 'provinsi_id' => '35'],
['id_kabupaten' => '3518', 'nama_kabupaten' => 'Kab. Nganjuk', 'provinsi_id' => '35'],
['id_kabupaten' => '3519', 'nama_kabupaten' => 'Kab. Madiun', 'provinsi_id' => '35'],
['id_kabupaten' => '3520', 'nama_kabupaten' => 'Kab. Magetan', 'provinsi_id' => '35'],
['id_kabupaten' => '3521', 'nama_kabupaten' => 'Kab. Ngawi', 'provinsi_id' => '35'],
['id_kabupaten' => '3522', 'nama_kabupaten' => 'Kab. Bojonegoro', 'provinsi_id' => '35'],
['id_kabupaten' => '3523', 'nama_kabupaten' => 'Kab. Tuban', 'provinsi_id' => '35'],
['id_kabupaten' => '3524', 'nama_kabupaten' => 'Kab. Lamongan', 'provinsi_id' => '35'],
['id_kabupaten' => '3525', 'nama_kabupaten' => 'Kab. Gresik', 'provinsi_id' => '35'],
['id_kabupaten' => '3526', 'nama_kabupaten' => 'Kab. Bangkalan', 'provinsi_id' => '35'],
['id_kabupaten' => '3527', 'nama_kabupaten' => 'Kab. Sampang', 'provinsi_id' => '35'],
['id_kabupaten' => '3528', 'nama_kabupaten' => 'Kab. Pamekasan', 'provinsi_id' => '35'],
['id_kabupaten' => '3529', 'nama_kabupaten' => 'Kab. Sumenep', 'provinsi_id' => '35'],
['id_kabupaten' => '3571', 'nama_kabupaten' => 'Kota Kediri', 'provinsi_id' => '35'],
['id_kabupaten' => '3572', 'nama_kabupaten' => 'Kota Blitar', 'provinsi_id' => '35'],
['id_kabupaten' => '3573', 'nama_kabupaten' => 'Kota Malang', 'provinsi_id' => '35'],
['id_kabupaten' => '3574', 'nama_kabupaten' => 'Kota Probolinggo', 'provinsi_id' => '35'],
['id_kabupaten' => '3575', 'nama_kabupaten' => 'Kota Pasuruan', 'provinsi_id' => '35'],
['id_kabupaten' => '3576', 'nama_kabupaten' => 'Kota Mojokerto', 'provinsi_id' => '35'],
['id_kabupaten' => '3577', 'nama_kabupaten' => 'Kota Madiun', 'provinsi_id' => '35'],
['id_kabupaten' => '3578', 'nama_kabupaten' => 'Kota Surabaya', 'provinsi_id' => '35'],
['id_kabupaten' => '3579', 'nama_kabupaten' => 'Kota Batu', 'provinsi_id' => '35'],
['id_kabupaten' => '3601', 'nama_kabupaten' => 'Kab. Pandeglang', 'provinsi_id' => '36'],
['id_kabupaten' => '3602', 'nama_kabupaten' => 'Kab. Lebak', 'provinsi_id' => '36'],
['id_kabupaten' => '3603', 'nama_kabupaten' => 'Kab. Tangerang', 'provinsi_id' => '36'],
['id_kabupaten' => '3604', 'nama_kabupaten' => 'Kab. Serang', 'provinsi_id' => '36'],
['id_kabupaten' => '3671', 'nama_kabupaten' => 'Kota Tangerang', 'provinsi_id' => '36'],
['id_kabupaten' => '3672', 'nama_kabupaten' => 'Kota Cilegon', 'provinsi_id' => '36'],
['id_kabupaten' => '3673', 'nama_kabupaten' => 'Kota Serang', 'provinsi_id' => '36'],
['id_kabupaten' => '3674', 'nama_kabupaten' => 'Kota Tangerang Selatan', 'provinsi_id' => '36'],
['id_kabupaten' => '5101', 'nama_kabupaten' => 'Kab. Jembrana', 'provinsi_id' => '51'],
['id_kabupaten' => '5102', 'nama_kabupaten' => 'Kab. Tabanan', 'provinsi_id' => '51'],
['id_kabupaten' => '5103', 'nama_kabupaten' => 'Kab. Badung', 'provinsi_id' => '51'],
['id_kabupaten' => '5104', 'nama_kabupaten' => 'Kab. Gianyar', 'provinsi_id' => '51'],
['id_kabupaten' => '5105', 'nama_kabupaten' => 'Kab. Klungkung', 'provinsi_id' => '51'],
['id_kabupaten' => '5106', 'nama_kabupaten' => 'Kab. Bangli', 'provinsi_id' => '51'],
['id_kabupaten' => '5107', 'nama_kabupaten' => 'Kab. Karang Asem', 'provinsi_id' => '51'],
['id_kabupaten' => '5108', 'nama_kabupaten' => 'Kab. Buleleng', 'provinsi_id' => '51'],
['id_kabupaten' => '5171', 'nama_kabupaten' => 'Kota Denpasar', 'provinsi_id' => '51'],
['id_kabupaten' => '5201', 'nama_kabupaten' => 'Kab. Lombok Barat', 'provinsi_id' => '52'],
['id_kabupaten' => '5202', 'nama_kabupaten' => 'Kab. Lombok Tengah', 'provinsi_id' => '52'],
['id_kabupaten' => '5203', 'nama_kabupaten' => 'Kab. Lombok Timur', 'provinsi_id' => '52'],
['id_kabupaten' => '5204', 'nama_kabupaten' => 'Kab. Sumbawa', 'provinsi_id' => '52'],
['id_kabupaten' => '5205', 'nama_kabupaten' => 'Kab. Dompu', 'provinsi_id' => '52'],
['id_kabupaten' => '5206', 'nama_kabupaten' => 'Kab. Bima', 'provinsi_id' => '52'],
['id_kabupaten' => '5207', 'nama_kabupaten' => 'Kab. Sumbawa Barat', 'provinsi_id' => '52'],
['id_kabupaten' => '5208', 'nama_kabupaten' => 'Kab. Lombok Utara', 'provinsi_id' => '52'],
['id_kabupaten' => '5271', 'nama_kabupaten' => 'Kota Mataram', 'provinsi_id' => '52'],
['id_kabupaten' => '5272', 'nama_kabupaten' => 'Kota Bima', 'provinsi_id' => '52'],
['id_kabupaten' => '5301', 'nama_kabupaten' => 'Kab. Sumba Barat', 'provinsi_id' => '53'],
['id_kabupaten' => '5302', 'nama_kabupaten' => 'Kab. Sumba Timur', 'provinsi_id' => '53'],
['id_kabupaten' => '5303', 'nama_kabupaten' => 'Kab. Kupang', 'provinsi_id' => '53'],
['id_kabupaten' => '5304', 'nama_kabupaten' => 'Kab. Timor Tengah Selatan', 'provinsi_id' => '53'],
['id_kabupaten' => '5305', 'nama_kabupaten' => 'Kab. Timor Tengah Utara', 'provinsi_id' => '53'],
['id_kabupaten' => '5306', 'nama_kabupaten' => 'Kab. Belu', 'provinsi_id' => '53'],
['id_kabupaten' => '5307', 'nama_kabupaten' => 'Kab. Alor', 'provinsi_id' => '53'],
['id_kabupaten' => '5308', 'nama_kabupaten' => 'Kab. Lembata', 'provinsi_id' => '53'],
['id_kabupaten' => '5309', 'nama_kabupaten' => 'Kab. Flores Timur', 'provinsi_id' => '53'],
['id_kabupaten' => '5310', 'nama_kabupaten' => 'Kab. Sikka', 'provinsi_id' => '53'],
['id_kabupaten' => '5311', 'nama_kabupaten' => 'Kab. Ende', 'provinsi_id' => '53'],
['id_kabupaten' => '5312', 'nama_kabupaten' => 'Kab. Ngada', 'provinsi_id' => '53'],
['id_kabupaten' => '5313', 'nama_kabupaten' => 'Kab. Manggarai', 'provinsi_id' => '53'],
['id_kabupaten' => '5314', 'nama_kabupaten' => 'Kab. Rote Ndao', 'provinsi_id' => '53'],
['id_kabupaten' => '5315', 'nama_kabupaten' => 'Kab. Manggarai Barat', 'provinsi_id' => '53'],
['id_kabupaten' => '5316', 'nama_kabupaten' => 'Kab. Sumba Tengah', 'provinsi_id' => '53'],
['id_kabupaten' => '5317', 'nama_kabupaten' => 'Kab. Sumba Barat Daya', 'provinsi_id' => '53'],
['id_kabupaten' => '5318', 'nama_kabupaten' => 'Kab. Nagekeo', 'provinsi_id' => '53'],
['id_kabupaten' => '5319', 'nama_kabupaten' => 'Kab. Manggarai Timur', 'provinsi_id' => '53'],
['id_kabupaten' => '5320', 'nama_kabupaten' => 'Kab. Sabu Raijua', 'provinsi_id' => '53'],
['id_kabupaten' => '5371', 'nama_kabupaten' => 'Kota Kupang', 'provinsi_id' => '53'],
['id_kabupaten' => '6101', 'nama_kabupaten' => 'Kab. Sambas', 'provinsi_id' => '61'],
['id_kabupaten' => '6102', 'nama_kabupaten' => 'Kab. Bengkayang', 'provinsi_id' => '61'],
['id_kabupaten' => '6103', 'nama_kabupaten' => 'Kab. Landak', 'provinsi_id' => '61'],
['id_kabupaten' => '6104', 'nama_kabupaten' => 'Kab. Pontianak', 'provinsi_id' => '61'],
['id_kabupaten' => '6105', 'nama_kabupaten' => 'Kab. Sanggau', 'provinsi_id' => '61'],
['id_kabupaten' => '6106', 'nama_kabupaten' => 'Kab. Ketapang', 'provinsi_id' => '61'],
['id_kabupaten' => '6107', 'nama_kabupaten' => 'Kab. Sintang', 'provinsi_id' => '61'],
['id_kabupaten' => '6108', 'nama_kabupaten' => 'Kab. Kapuas Hulu', 'provinsi_id' => '61'],
['id_kabupaten' => '6109', 'nama_kabupaten' => 'Kab. Sekadau', 'provinsi_id' => '61'],
['id_kabupaten' => '6110', 'nama_kabupaten' => 'Kab. Melawi', 'provinsi_id' => '61'],
['id_kabupaten' => '6111', 'nama_kabupaten' => 'Kab. Kayong Utara', 'provinsi_id' => '61'],
['id_kabupaten' => '6112', 'nama_kabupaten' => 'Kab. Kubu Raya', 'provinsi_id' => '61'],
['id_kabupaten' => '6171', 'nama_kabupaten' => 'Kota Pontianak', 'provinsi_id' => '61'],
['id_kabupaten' => '6172', 'nama_kabupaten' => 'Kota Singkawang', 'provinsi_id' => '61'],
['id_kabupaten' => '6201', 'nama_kabupaten' => 'Kab. Kotawaringin Barat', 'provinsi_id' => '62'],
['id_kabupaten' => '6202', 'nama_kabupaten' => 'Kab. Kotawaringin Timur', 'provinsi_id' => '62'],
['id_kabupaten' => '6203', 'nama_kabupaten' => 'Kab. Kapuas', 'provinsi_id' => '62'],
['id_kabupaten' => '6204', 'nama_kabupaten' => 'Kab. Barito Selatan', 'provinsi_id' => '62'],
['id_kabupaten' => '6205', 'nama_kabupaten' => 'Kab. Barito Utara', 'provinsi_id' => '62'],
['id_kabupaten' => '6206', 'nama_kabupaten' => 'Kab. Sukamara', 'provinsi_id' => '62'],
['id_kabupaten' => '6207', 'nama_kabupaten' => 'Kab. Lamandau', 'provinsi_id' => '62'],
['id_kabupaten' => '6208', 'nama_kabupaten' => 'Kab. Seruyan', 'provinsi_id' => '62'],
['id_kabupaten' => '6209', 'nama_kabupaten' => 'Kab. Katingan', 'provinsi_id' => '62'],
['id_kabupaten' => '6210', 'nama_kabupaten' => 'Kab. Pulang Pisau', 'provinsi_id' => '62'],
['id_kabupaten' => '6211', 'nama_kabupaten' => 'Kab. Gunung Mas', 'provinsi_id' => '62'],
['id_kabupaten' => '6212', 'nama_kabupaten' => 'Kab. Barito Timur', 'provinsi_id' => '62'],
['id_kabupaten' => '6213', 'nama_kabupaten' => 'Kab. Murung Raya', 'provinsi_id' => '62'],
['id_kabupaten' => '6271', 'nama_kabupaten' => 'Kota Palangka Raya', 'provinsi_id' => '62'],
['id_kabupaten' => '6301', 'nama_kabupaten' => 'Kab. Tanah Laut', 'provinsi_id' => '63'],
['id_kabupaten' => '6302', 'nama_kabupaten' => 'Kab. Kota Baru', 'provinsi_id' => '63'],
['id_kabupaten' => '6303', 'nama_kabupaten' => 'Kab. Banjar', 'provinsi_id' => '63'],
['id_kabupaten' => '6304', 'nama_kabupaten' => 'Kab. Barito Kuala', 'provinsi_id' => '63'],
['id_kabupaten' => '6305', 'nama_kabupaten' => 'Kab. Tapin', 'provinsi_id' => '63'],
['id_kabupaten' => '6306', 'nama_kabupaten' => 'Kab. Hulu Sungai Selatan', 'provinsi_id' => '63'],
['id_kabupaten' => '6307', 'nama_kabupaten' => 'Kab. Hulu Sungai Tengah', 'provinsi_id' => '63'],
['id_kabupaten' => '6308', 'nama_kabupaten' => 'Kab. Hulu Sungai Utara', 'provinsi_id' => '63'],
['id_kabupaten' => '6309', 'nama_kabupaten' => 'Kab. Tabalong', 'provinsi_id' => '63'],
['id_kabupaten' => '6310', 'nama_kabupaten' => 'Kab. Tanah Bumbu', 'provinsi_id' => '63'],
['id_kabupaten' => '6311', 'nama_kabupaten' => 'Kab. Balangan', 'provinsi_id' => '63'],
['id_kabupaten' => '6371', 'nama_kabupaten' => 'Kota Banjarmasin', 'provinsi_id' => '63'],
['id_kabupaten' => '6372', 'nama_kabupaten' => 'Kota Banjar Baru', 'provinsi_id' => '63'],
['id_kabupaten' => '6401', 'nama_kabupaten' => 'Kab. Paser', 'provinsi_id' => '64'],
['id_kabupaten' => '6402', 'nama_kabupaten' => 'Kab. Kutai Barat', 'provinsi_id' => '64'],
['id_kabupaten' => '6403', 'nama_kabupaten' => 'Kab. Kutai Kartanegara', 'provinsi_id' => '64'],
['id_kabupaten' => '6404', 'nama_kabupaten' => 'Kab. Kutai Timur', 'provinsi_id' => '64'],
['id_kabupaten' => '6405', 'nama_kabupaten' => 'Kab. Berau', 'provinsi_id' => '64'],
['id_kabupaten' => '6409', 'nama_kabupaten' => 'Kab. Penajam Paser Utara', 'provinsi_id' => '64'],
['id_kabupaten' => '6471', 'nama_kabupaten' => 'Kota Balikpapan', 'provinsi_id' => '64'],
['id_kabupaten' => '6472', 'nama_kabupaten' => 'Kota Samarinda', 'provinsi_id' => '64'],
['id_kabupaten' => '6474', 'nama_kabupaten' => 'Kota Bontang', 'provinsi_id' => '64'],
['id_kabupaten' => '6501', 'nama_kabupaten' => 'Kab. Malinau', 'provinsi_id' => '65'],
['id_kabupaten' => '6502', 'nama_kabupaten' => 'Kab. Bulungan', 'provinsi_id' => '65'],
['id_kabupaten' => '6503', 'nama_kabupaten' => 'Kab. Tana Tidung', 'provinsi_id' => '65'],
['id_kabupaten' => '6504', 'nama_kabupaten' => 'Kab. Nunukan', 'provinsi_id' => '65'],
['id_kabupaten' => '6571', 'nama_kabupaten' => 'Kota Tarakan', 'provinsi_id' => '65'],
['id_kabupaten' => '7101', 'nama_kabupaten' => 'Kab. Bolaang Mongondow', 'provinsi_id' => '71'],
['id_kabupaten' => '7102', 'nama_kabupaten' => 'Kab. Minahasa', 'provinsi_id' => '71'],
['id_kabupaten' => '7103', 'nama_kabupaten' => 'Kab. Kepulauan Sangihe', 'provinsi_id' => '71'],
['id_kabupaten' => '7104', 'nama_kabupaten' => 'Kab. Kepulauan Talaud', 'provinsi_id' => '71'],
['id_kabupaten' => '7105', 'nama_kabupaten' => 'Kab. Minahasa Selatan', 'provinsi_id' => '71'],
['id_kabupaten' => '7106', 'nama_kabupaten' => 'Kab. Minahasa Utara', 'provinsi_id' => '71'],
['id_kabupaten' => '7107', 'nama_kabupaten' => 'Kab. Bolaang Mongondow Utara', 'provinsi_id' => '71'],
['id_kabupaten' => '7108', 'nama_kabupaten' => 'Kab. Siau Tagulandang Biaro', 'provinsi_id' => '71'],
['id_kabupaten' => '7109', 'nama_kabupaten' => 'Kab. Minahasa Tenggara', 'provinsi_id' => '71'],
['id_kabupaten' => '7110', 'nama_kabupaten' => 'Kab. Bolaang Mongondow Selatan', 'provinsi_id' => '71'],
['id_kabupaten' => '7111', 'nama_kabupaten' => 'Kab. Bolaang Mongondow Timur', 'provinsi_id' => '71'],
['id_kabupaten' => '7171', 'nama_kabupaten' => 'Kota Manado', 'provinsi_id' => '71'],
['id_kabupaten' => '7172', 'nama_kabupaten' => 'Kota Bitung', 'provinsi_id' => '71'],
['id_kabupaten' => '7173', 'nama_kabupaten' => 'Kota Tomohon', 'provinsi_id' => '71'],
['id_kabupaten' => '7174', 'nama_kabupaten' => 'Kota Kotamobagu', 'provinsi_id' => '71'],
['id_kabupaten' => '7201', 'nama_kabupaten' => 'Kab. Banggai Kepulauan', 'provinsi_id' => '72'],
['id_kabupaten' => '7202', 'nama_kabupaten' => 'Kab. Banggai', 'provinsi_id' => '72'],
['id_kabupaten' => '7203', 'nama_kabupaten' => 'Kab. Morowali', 'provinsi_id' => '72'],
['id_kabupaten' => '7204', 'nama_kabupaten' => 'Kab. Poso', 'provinsi_id' => '72'],
['id_kabupaten' => '7205', 'nama_kabupaten' => 'Kab. Donggala', 'provinsi_id' => '72'],
['id_kabupaten' => '7206', 'nama_kabupaten' => 'Kab. Toli-toli', 'provinsi_id' => '72'],
['id_kabupaten' => '7207', 'nama_kabupaten' => 'Kab. Buol', 'provinsi_id' => '72'],
['id_kabupaten' => '7208', 'nama_kabupaten' => 'Kab. Parigi Moutong', 'provinsi_id' => '72'],
['id_kabupaten' => '7209', 'nama_kabupaten' => 'Kab. Tojo Una-una', 'provinsi_id' => '72'],
['id_kabupaten' => '7210', 'nama_kabupaten' => 'Kab. Sigi', 'provinsi_id' => '72'],
['id_kabupaten' => '7271', 'nama_kabupaten' => 'Kota Palu', 'provinsi_id' => '72'],
['id_kabupaten' => '7301', 'nama_kabupaten' => 'Kab. Kepulauan Selayar', 'provinsi_id' => '73'],
['id_kabupaten' => '7302', 'nama_kabupaten' => 'Kab. Bulukumba', 'provinsi_id' => '73'],
['id_kabupaten' => '7303', 'nama_kabupaten' => 'Kab. Bantaeng', 'provinsi_id' => '73'],
['id_kabupaten' => '7304', 'nama_kabupaten' => 'Kab. Jeneponto', 'provinsi_id' => '73'],
['id_kabupaten' => '7305', 'nama_kabupaten' => 'Kab. Takalar', 'provinsi_id' => '73'],
['id_kabupaten' => '7306', 'nama_kabupaten' => 'Kab. Gowa', 'provinsi_id' => '73'],
['id_kabupaten' => '7307', 'nama_kabupaten' => 'Kab. Sinjai', 'provinsi_id' => '73'],
['id_kabupaten' => '7308', 'nama_kabupaten' => 'Kab. Maros', 'provinsi_id' => '73'],
['id_kabupaten' => '7309', 'nama_kabupaten' => 'Kab. Pangkajene Dan Kepulauan', 'provinsi_id' => '73'],
['id_kabupaten' => '7310', 'nama_kabupaten' => 'Kab. Barru', 'provinsi_id' => '73'],
['id_kabupaten' => '7311', 'nama_kabupaten' => 'Kab. Bone', 'provinsi_id' => '73'],
['id_kabupaten' => '7312', 'nama_kabupaten' => 'Kab. Soppeng', 'provinsi_id' => '73'],
['id_kabupaten' => '7313', 'nama_kabupaten' => 'Kab. Wajo', 'provinsi_id' => '73'],
['id_kabupaten' => '7314', 'nama_kabupaten' => 'Kab. Sidenreng Rappang', 'provinsi_id' => '73'],
['id_kabupaten' => '7315', 'nama_kabupaten' => 'Kab. Pinrang', 'provinsi_id' => '73'],
['id_kabupaten' => '7316', 'nama_kabupaten' => 'Kab. Enrekang', 'provinsi_id' => '73'],
['id_kabupaten' => '7317', 'nama_kabupaten' => 'Kab. Luwu', 'provinsi_id' => '73'],
['id_kabupaten' => '7318', 'nama_kabupaten' => 'Kab. Tana Toraja', 'provinsi_id' => '73'],
['id_kabupaten' => '7322', 'nama_kabupaten' => 'Kab. Luwu Utara', 'provinsi_id' => '73'],
['id_kabupaten' => '7325', 'nama_kabupaten' => 'Kab. Luwu Timur', 'provinsi_id' => '73'],
['id_kabupaten' => '7326', 'nama_kabupaten' => 'Kab. Toraja Utara', 'provinsi_id' => '73'],
['id_kabupaten' => '7371', 'nama_kabupaten' => 'Kota Makassar', 'provinsi_id' => '73'],
['id_kabupaten' => '7372', 'nama_kabupaten' => 'Kota Parepare', 'provinsi_id' => '73'],
['id_kabupaten' => '7373', 'nama_kabupaten' => 'Kota Palopo', 'provinsi_id' => '73'],
['id_kabupaten' => '7401', 'nama_kabupaten' => 'Kab. Buton', 'provinsi_id' => '74'],
['id_kabupaten' => '7402', 'nama_kabupaten' => 'Kab. Muna', 'provinsi_id' => '74'],
['id_kabupaten' => '7403', 'nama_kabupaten' => 'Kab. Konawe', 'provinsi_id' => '74'],
['id_kabupaten' => '7404', 'nama_kabupaten' => 'Kab. Kolaka', 'provinsi_id' => '74'],
['id_kabupaten' => '7405', 'nama_kabupaten' => 'Kab. Konawe Selatan', 'provinsi_id' => '74'],
['id_kabupaten' => '7406', 'nama_kabupaten' => 'Kab. Bombana', 'provinsi_id' => '74'],
['id_kabupaten' => '7407', 'nama_kabupaten' => 'Kab. Wakatobi', 'provinsi_id' => '74'],
['id_kabupaten' => '7408', 'nama_kabupaten' => 'Kab. Kolaka Utara', 'provinsi_id' => '74'],
['id_kabupaten' => '7409', 'nama_kabupaten' => 'Kab. Buton Utara', 'provinsi_id' => '74'],
['id_kabupaten' => '7410', 'nama_kabupaten' => 'Kab. Konawe Utara', 'provinsi_id' => '74'],
['id_kabupaten' => '7471', 'nama_kabupaten' => 'Kota Kendari', 'provinsi_id' => '74'],
['id_kabupaten' => '7472', 'nama_kabupaten' => 'Kota Baubau', 'provinsi_id' => '74'],
['id_kabupaten' => '7501', 'nama_kabupaten' => 'Kab. Boalemo', 'provinsi_id' => '75'],
['id_kabupaten' => '7502', 'nama_kabupaten' => 'Kab. Gorontalo', 'provinsi_id' => '75'],
['id_kabupaten' => '7503', 'nama_kabupaten' => 'Kab. Pohuwato', 'provinsi_id' => '75'],
['id_kabupaten' => '7504', 'nama_kabupaten' => 'Kab. Bone Bolango', 'provinsi_id' => '75'],
['id_kabupaten' => '7505', 'nama_kabupaten' => 'Kab. Gorontalo Utara', 'provinsi_id' => '75'],
['id_kabupaten' => '7571', 'nama_kabupaten' => 'Kota Gorontalo', 'provinsi_id' => '75'],
['id_kabupaten' => '7601', 'nama_kabupaten' => 'Kab. Majene', 'provinsi_id' => '76'],
['id_kabupaten' => '7602', 'nama_kabupaten' => 'Kab. Polewali Mandar', 'provinsi_id' => '76'],
['id_kabupaten' => '7603', 'nama_kabupaten' => 'Kab. Mamasa', 'provinsi_id' => '76'],
['id_kabupaten' => '7604', 'nama_kabupaten' => 'Kab. Mamuju', 'provinsi_id' => '76'],
['id_kabupaten' => '7605', 'nama_kabupaten' => 'Kab. Mamuju Utara', 'provinsi_id' => '76'],
['id_kabupaten' => '8101', 'nama_kabupaten' => 'Kab. Maluku Tenggara Barat', 'provinsi_id' => '81'],
['id_kabupaten' => '8102', 'nama_kabupaten' => 'Kab. Maluku Tenggara', 'provinsi_id' => '81'],
['id_kabupaten' => '8103', 'nama_kabupaten' => 'Kab. Maluku Tengah', 'provinsi_id' => '81'],
['id_kabupaten' => '8104', 'nama_kabupaten' => 'Kab. Buru', 'provinsi_id' => '81'],
['id_kabupaten' => '8105', 'nama_kabupaten' => 'Kab. Kepulauan Aru', 'provinsi_id' => '81'],
['id_kabupaten' => '8106', 'nama_kabupaten' => 'Kab. Seram Bagian Barat', 'provinsi_id' => '81'],
['id_kabupaten' => '8107', 'nama_kabupaten' => 'Kab. Seram Bagian Timur', 'provinsi_id' => '81'],
['id_kabupaten' => '8108', 'nama_kabupaten' => 'Kab. Maluku Barat Daya', 'provinsi_id' => '81'],
['id_kabupaten' => '8109', 'nama_kabupaten' => 'Kab. Buru Selatan', 'provinsi_id' => '81'],
['id_kabupaten' => '8171', 'nama_kabupaten' => 'Kota Ambon', 'provinsi_id' => '81'],
['id_kabupaten' => '8172', 'nama_kabupaten' => 'Kota Tual', 'provinsi_id' => '81'],
['id_kabupaten' => '8201', 'nama_kabupaten' => 'Kab. Halmahera Barat', 'provinsi_id' => '82'],
['id_kabupaten' => '8202', 'nama_kabupaten' => 'Kab. Halmahera Tengah', 'provinsi_id' => '82'],
['id_kabupaten' => '8203', 'nama_kabupaten' => 'Kab. Kepulauan Sula', 'provinsi_id' => '82'],
['id_kabupaten' => '8204', 'nama_kabupaten' => 'Kab. Halmahera Selatan', 'provinsi_id' => '82'],
['id_kabupaten' => '8205', 'nama_kabupaten' => 'Kab. Halmahera Utara', 'provinsi_id' => '82'],
['id_kabupaten' => '8206', 'nama_kabupaten' => 'Kab. Halmahera Timur', 'provinsi_id' => '82'],
['id_kabupaten' => '8207', 'nama_kabupaten' => 'Kab. Pulau Morotai', 'provinsi_id' => '82'],
['id_kabupaten' => '8271', 'nama_kabupaten' => 'Kota Ternate', 'provinsi_id' => '82'],
['id_kabupaten' => '8272', 'nama_kabupaten' => 'Kota Tidore Kepulauan', 'provinsi_id' => '82'],
['id_kabupaten' => '9101', 'nama_kabupaten' => 'Kab. Fakfak', 'provinsi_id' => '91'],
['id_kabupaten' => '9102', 'nama_kabupaten' => 'Kab. Kaimana', 'provinsi_id' => '91'],
['id_kabupaten' => '9103', 'nama_kabupaten' => 'Kab. Teluk Wondama', 'provinsi_id' => '91'],
['id_kabupaten' => '9104', 'nama_kabupaten' => 'Kab. Teluk Bintuni', 'provinsi_id' => '91'],
['id_kabupaten' => '9105', 'nama_kabupaten' => 'Kab. Manokwari', 'provinsi_id' => '91'],
['id_kabupaten' => '9106', 'nama_kabupaten' => 'Kab. Sorong Selatan', 'provinsi_id' => '91'],
['id_kabupaten' => '9107', 'nama_kabupaten' => 'Kab. Sorong', 'provinsi_id' => '91'],
['id_kabupaten' => '9108', 'nama_kabupaten' => 'Kab. Raja Ampat', 'provinsi_id' => '91'],
['id_kabupaten' => '9109', 'nama_kabupaten' => 'Kab. Tambrauw', 'provinsi_id' => '91'],
['id_kabupaten' => '9110', 'nama_kabupaten' => 'Kab. Maybrat', 'provinsi_id' => '91'],
['id_kabupaten' => '9171', 'nama_kabupaten' => 'Kota Sorong', 'provinsi_id' => '91'],
['id_kabupaten' => '9401', 'nama_kabupaten' => 'Kab. Merauke', 'provinsi_id' => '94'],
['id_kabupaten' => '9402', 'nama_kabupaten' => 'Kab. Jayawijaya', 'provinsi_id' => '94'],
['id_kabupaten' => '9403', 'nama_kabupaten' => 'Kab. Jayapura', 'provinsi_id' => '94'],
['id_kabupaten' => '9404', 'nama_kabupaten' => 'Kab. Nabire', 'provinsi_id' => '94'],
['id_kabupaten' => '9408', 'nama_kabupaten' => 'Kab. Kepulauan Yapen', 'provinsi_id' => '94'],
['id_kabupaten' => '9409', 'nama_kabupaten' => 'Kab. Biak Numfor', 'provinsi_id' => '94'],
['id_kabupaten' => '9410', 'nama_kabupaten' => 'Kab. Paniai', 'provinsi_id' => '94'],
['id_kabupaten' => '9411', 'nama_kabupaten' => 'Kab. Puncak Jaya', 'provinsi_id' => '94'],
['id_kabupaten' => '9412', 'nama_kabupaten' => 'Kab. Mimika', 'provinsi_id' => '94'],
['id_kabupaten' => '9413', 'nama_kabupaten' => 'Kab. Boven Digoel', 'provinsi_id' => '94'],
['id_kabupaten' => '9414', 'nama_kabupaten' => 'Kab. Mappi', 'provinsi_id' => '94'],
['id_kabupaten' => '9415', 'nama_kabupaten' => 'Kab. Asmat', 'provinsi_id' => '94'],
['id_kabupaten' => '9416', 'nama_kabupaten' => 'Kab. Yahukimo', 'provinsi_id' => '94'],
['id_kabupaten' => '9417', 'nama_kabupaten' => 'Kab. Pegunungan Bintang', 'provinsi_id' => '94'],
['id_kabupaten' => '9418', 'nama_kabupaten' => 'Kab. Tolikara', 'provinsi_id' => '94'],
['id_kabupaten' => '9419', 'nama_kabupaten' => 'Kab. Sarmi', 'provinsi_id' => '94'],
['id_kabupaten' => '9420', 'nama_kabupaten' => 'Kab. Keerom', 'provinsi_id' => '94'],
['id_kabupaten' => '9426', 'nama_kabupaten' => 'Kab. Waropen', 'provinsi_id' => '94'],
['id_kabupaten' => '9427', 'nama_kabupaten' => 'Kab. Supiori', 'provinsi_id' => '94'],
['id_kabupaten' => '9428', 'nama_kabupaten' => 'Kab. Mamberamo Raya', 'provinsi_id' => '94'],
['id_kabupaten' => '9429', 'nama_kabupaten' => 'Kab. Nduga', 'provinsi_id' => '94'],
['id_kabupaten' => '9430', 'nama_kabupaten' => 'Kab. Lanny Jaya', 'provinsi_id' => '94'],
['id_kabupaten' => '9431', 'nama_kabupaten' => 'Kab. Mamberamo Tengah', 'provinsi_id' => '94'],
['id_kabupaten' => '9432', 'nama_kabupaten' => 'Kab. Yalimo', 'provinsi_id' => '94'],
['id_kabupaten' => '9433', 'nama_kabupaten' => 'Kab. Puncak', 'provinsi_id' => '94'],
['id_kabupaten' => '9434', 'nama_kabupaten' => 'Kab. Dogiyai', 'provinsi_id' => '94'],
['id_kabupaten' => '9435', 'nama_kabupaten' => 'Kab. Intan Jaya', 'provinsi_id' => '94'],
['id_kabupaten' => '9436', 'nama_kabupaten' => 'Kab. Deiyai', 'provinsi_id' => '94'],
['id_kabupaten' => '9471', 'nama_kabupaten' => 'Kota Jayapura', 'provinsi_id' => '94'],
];